name: lumina_pro
description: "Bit-Perfect Audio Player"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path_provider: ^2.1.2
  path: ^1.9.0
  metadata_god: ^0.5.0
  google_fonts: ^6.2.1
  share_plus: ^9.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  http: ^1.2.0
  wakelock_plus: 1.2.8
  fftea: ^1.5.0+1
  scrollable_positioned_list: ^0.3.8
  ffmpeg_kit_flutter:
    git:
      url: https://github.com/Sahad2701/ffmpeg-kit.git
      path: flutter/flutter
      ref: flutter_fix_retired_v6.0.3


  # dsp_plugin is injected by the GitHub Actions workflow
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
